ALTER TABLE `users`
  ADD COLUMN `goalPeriod` VARCHAR(16) NOT NULL DEFAULT 'week',
  ADD COLUMN `goalMode` VARCHAR(16) NOT NULL DEFAULT 'count',
  ADD COLUMN `goalCount` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `goalDuration` INTEGER NOT NULL DEFAULT 30;

UPDATE `users`
SET `goalCount` = CASE
  WHEN `dailyGoal` BETWEEN 1 AND 10 THEN `dailyGoal`
  ELSE 1
END
WHERE `goalCount` = 1;
