ALTER TABLE `users`
  ADD COLUMN `goalPeriod` VARCHAR(16) NOT NULL DEFAULT 'week',
  ADD COLUMN `goalMode` VARCHAR(16) NOT NULL DEFAULT 'count',
  ADD COLUMN `goalCount` INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN `goalDuration` INTEGER NOT NULL DEFAULT 180;
